# Notebooks.
notebooks-source: notebooks
notebooks-target: notebooks
master-target: master
demos-target: demos

# Other content.
references-source: references
references-target: references
scripts-source: scripts
images-source: images
images-target: images

# AWS S3 storage.
s3-bucket: kosu-demo
s3-path: data  # Optional

# All courses.
all:
  - example_course
